### ISSUE TITLE
[Slurm collector] Wrong time conversion

### ISSUE THREAD

**Issue by dirksammel** [ALU-Schumacher/AUDITOR#427]
The slurm collector currently converts several time information from the `sacct` command (SystemCPU, UserCPU, TotalCPU) to milliseconds.
This created an issue with the APEL plugin, since the plugin expects (and reports) this information in seconds. 
So this needs to be adjusted in either the collector or the plugin. Opinions on this?

Another problem is the conversion from hours to ms: the conversion factor currently used is `1_440_000`, but I think it should be `3_600_000` (`1h = 60m = 60*60s = 60*60*1000ms = 3_600_000`), but maybe I'm missing something?

https://github.com/ALU-Schumacher/AUDITOR/blob/fdb4d604b10f5b6d1513ec12cc4c620ed157ce3d/collectors/slurm/src/configuration.rs#L378-L383

**Comment by QuantumDancer** [comment]
Yes, there is an error in the conversion from hours to milliseconds. In addition, there is also an issue when parsing time strings in the format of `D-HH:MM:SS`. Here, the day part is ignored. This will be fixed with #433.

Regarding the question of storing seconds or milliseconds: I think we should store milliseconds, otherwise we throw away data. Then, each plugin can decide if the times should be converted to seconds or not.

**Comment by dirksammel** [comment]
> Regarding the question of storing seconds or milliseconds: I think we should store milliseconds, otherwise we throw away data. Then, each plugin can decide if the times should be converted to seconds or not.

Yes, I agree.
